name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t DOCKER_USERNAME/backend:latest ./backend
          docker push DOCKER_USERNAME/backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t DOCKER_USERNAME/frontend:latest ./frontend
          docker push DOCKER_USERNAME/frontend:latest

      - name: Deploy Docker Containers on EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/mean-app   
            docker-compose pull
            docker-compose down
            docker-compose up -d
          EOF
